/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FormFormIdRouteImport } from './routes/form/$formId'
import { Route as ReportReportIdRouteImport } from './routes/report/$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FormFormIdRoute = FormFormIdRouteImport.update({
  id: '/form/$formId',
  path: '/form/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportReportIdRoute = ReportReportIdRouteImport.update({
  id: '/report/$reportId',
  path: '/report/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/form/$formId': typeof FormFormIdRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/form/$formId': typeof FormFormIdRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/form/$formId': typeof FormFormIdRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/form/$formId' | '/report/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/form/$formId' | '/report/$reportId'
  id: '__root__' | '/' | '/dashboard' | '/form/$formId' | '/report/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FormFormIdRoute: typeof FormFormIdRoute
  ReportReportIdRoute: typeof ReportReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$formId': {
      id: '/form/$formId'
      path: '/form/$formId'
      fullPath: '/form/$formId'
      preLoaderRoute: typeof FormFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$reportId': {
      id: '/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/report/$reportId'
      preLoaderRoute: typeof ReportReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FormFormIdRoute: FormFormIdRoute,
  ReportReportIdRoute: ReportReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
